apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecjobs-ingress
  namespace: devsecjobs
spec:
  rules:
  - host: devsecjobs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: api.devsecjobs.local
    http:
      paths:            
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5001