kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-config
  namespace: devsecjobs
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  PORT: "5001"
  JWT_ACCESS_EXPIRES_MIN: "60"
  JWT_REFRESH_EXPIRES_DAYS: "7"
  CORS_ORIGINS: "*"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend-config
  namespace: devsecjobs
data:
  VITE_API_BASE_URL: "http://backend-service:5001"

