kind: Secret
apiVersion: v1
metadata:
  name: db-credentials
  namespace: DecSecJobs
type: Opaque
data:
  DB_USER: cm9vdA==              # root
  DB_PASSWORD: cGFzc3dvcmQ=      # password
  DB_HOST: bXlzcWw=              # mysql (שם ה-service!)
  DB_NAME: ZGV2c2Vjb3BzMjBiaXU=  # devsecops20biu

---
kind: Secret
apiVersion: v1
metadata:
  name: jwt-secret
  namespace: DecSecJobs
type: Opaque
data:
  JWT_SECRET_KEY: c2VjdXJlX2tleV9mb3Jfand0 # secure_key_for_jwt  