kind: Secret
apiVersion: v1
metadata:
  name: db-credentials
  namespace: devsecjobs
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootStrongPass123"
  MYSQL_DATABASE: "devsecjobs"
  MYSQL_USER: "devsecjobs_user"
  MYSQL_PASSWORD: "devsecjobs_pass"

  DB_HOST: "mysql-service"
  DB_NAME: "devsecjobs"
  DB_USER: "devsecjobs_user"
  DB_PASSWORD: "devsecjobs_pass"
---
kind: Secret
apiVersion: v1
metadata:
  name: jwt-secret
  namespace: devsecjobs
type: Opaque
data:
  JWT_SECRET_KEY: c2VjdXJlX2tleV9mb3Jfand0 # secure_key_for_jwt  